# Generated by Django 5.1.3 on 2024-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilmImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="film_images/")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Easy", "easy"),
                            ("Medium", "medium"),
                            ("Hard", "hard"),
                        ],
                        max_length=6,
                    ),
                ),
                ("hint_1", models.CharField(blank=True, max_length=255, null=True)),
                ("hint_2", models.CharField(blank=True, max_length=255, null=True)),
                ("hint_3", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("score", models.PositiveIntegerField(default=0)),
                ("time_remaining", models.PositiveIntegerField(default=90)),
                (
                    "images_remaining",
                    models.ManyToManyField(
                        related_name="sessions", to="game.filmimage"
                    ),
                ),
            ],
        ),
    ]
