# Generated by Django 5.1.3 on 2024-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmimage",
            name="frame",
            field=models.CharField(
                choices=[("first", "First Frame"), ("last", "Last Frame")],
                default="first",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="frame_mode",
            field=models.CharField(
                choices=[("first", "First Frame"), ("last", "Last Frame")],
                default="first",
                max_length=5,
            ),
        ),
    ]
