# Generated by Django 5.1.3 on 2024-11-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_filmimage_frame_gamesession_frame_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmimage",
            name="hint_3",
        ),
    ]
