# Generated by Django 5.1.3 on 2024-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_filmimage_hint_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
