# Generated by Django 5.1.3 on 2024-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_gamesession_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmimage",
            name="incorrect_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
