# Generated by Django 5.1.3 on 2024-12-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_filmimage_incorrect_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmimage",
            name="incorrect_attempts",
        ),
    ]
