# Generated by Django 5.1.3 on 2024-12-12 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_remove_filmimage_incorrect_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="current_tier_shown",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
